new obj-c style docs
muxinc/mux-docs pull request #8
Opened 2016-11-18 22:48 UTC by theRealWardo

2016-11-18 23:17 UTC, jsanford8 approved these changes
(redacted)

2016-11-18 23:19 UTC, jsanford8 requested changes

2016-11-18 23:19 UTC, jsanford8 commented on source/index.html.md
> +  Include the correct Mux Objective-C SDK for your project by cloning our repository and dragging the framework into your Xcode project. The <code>Frameworks</code> folder contains two folders, one f
Remove the `is` in the `This is library cannot be used`

2016-11-19 01:19 UTC, theRealWardo commented on source/index.html.md
> +  Include the correct Mux Objective-C SDK for your project by cloning our repository and dragging the framework into your Xcode project. The <code>Frameworks</code> folder contains two folders, one f
gotcha. done.

2016-11-19 01:42 UTC, merged